//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type MitDataWarehousePerson = $ModelResult<$Schema, "MitDataWarehousePerson">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type FailedLoginAttempt = $ModelResult<$Schema, "FailedLoginAttempt">;
export type AuditLog = $ModelResult<$Schema, "AuditLog">;
export type LegalAgreementAcceptance = $ModelResult<$Schema, "LegalAgreementAcceptance">;
export type SailingCardRequest = $ModelResult<$Schema, "SailingCardRequest">;
export type UserAudit = $ModelResult<$Schema, "UserAudit">;
export type SiteTextOverride = $ModelResult<$Schema, "SiteTextOverride">;
export type NewsletterSubscriber = $ModelResult<$Schema, "NewsletterSubscriber">;
export type NewsletterList = $ModelResult<$Schema, "NewsletterList">;
export type NewsletterSubscription = $ModelResult<$Schema, "NewsletterSubscription">;
export type NewsletterTemplate = $ModelResult<$Schema, "NewsletterTemplate">;
export type NewsletterBroadcast = $ModelResult<$Schema, "NewsletterBroadcast">;
export type NewsletterBroadcastList = $ModelResult<$Schema, "NewsletterBroadcastList">;
export type NewsletterDelivery = $ModelResult<$Schema, "NewsletterDelivery">;
export type NewsletterEvent = $ModelResult<$Schema, "NewsletterEvent">;
export type EmailMessage = $ModelResult<$Schema, "EmailMessage">;
export type EmailMessageEvent = $ModelResult<$Schema, "EmailMessageEvent">;
export type EventCategory = $ModelResult<$Schema, "EventCategory">;
export type Event = $ModelResult<$Schema, "Event">;
export type EventDate = $ModelResult<$Schema, "EventDate">;
export type EventAdmin = $ModelResult<$Schema, "EventAdmin">;
export type EventRegistration = $ModelResult<$Schema, "EventRegistration">;
export type EventRegistrationTeam = $ModelResult<$Schema, "EventRegistrationTeam">;
export type EventRegistrationBoatMember = $ModelResult<$Schema, "EventRegistrationBoatMember">;
export type EventRegistrationQuestion = $ModelResult<$Schema, "EventRegistrationQuestion">;
export type EventRegistrationAnswer = $ModelResult<$Schema, "EventRegistrationAnswer">;
/**
 * Event registration fee line item. **`amount_cents`** stores **integer USD cents**
 * (e.g. `1999` for $19.99), matching Stripe `amount` for `currency: "usd"` and
 * avoiding floating-point dollar columns in PostgreSQL.
 */
export type EventEntryFee = $ModelResult<$Schema, "EventEntryFee">;
export type Payment = $ModelResult<$Schema, "Payment">;
export type StripeWebhookEvent = $ModelResult<$Schema, "StripeWebhookEvent">;
export type EventPaymentNotification = $ModelResult<$Schema, "EventPaymentNotification">;
export type EventComment = $ModelResult<$Schema, "EventComment">;
export type ClassCategory = $ModelResult<$Schema, "ClassCategory">;
export type SailingClass = $ModelResult<$Schema, "SailingClass">;
export type SailingClassRelatedEvent = $ModelResult<$Schema, "SailingClassRelatedEvent">;
export type SailingClassPrerequisite = $ModelResult<$Schema, "SailingClassPrerequisite">;
export type SailingClassUnlockedBoat = $ModelResult<$Schema, "SailingClassUnlockedBoat">;
export type SailingRating = $ModelResult<$Schema, "SailingRating">;
export type UserSailingRating = $ModelResult<$Schema, "UserSailingRating">;
/**
 * Targets exactly one of boat, class, or rating (`boatId`, `classId`, or `ratingId`).
 * Enforced in Postgres by `sailing_rating_rules_exactly_one_target_chk` (migration `20260511193000_sailing_rating_rule_target_fks`).
 */
export type SailingRatingRule = $ModelResult<$Schema, "SailingRatingRule">;
export type FleetBoat = $ModelResult<$Schema, "FleetBoat">;
export type SiteAlert = $ModelResult<$Schema, "SiteAlert">;
export type CmsPage = $ModelResult<$Schema, "CmsPage">;
export type CmsPageBlock = $ModelResult<$Schema, "CmsPageBlock">;
export type CmsMediaAsset = $ModelResult<$Schema, "CmsMediaAsset">;
export type CmsMenu = $ModelResult<$Schema, "CmsMenu">;
export type CmsMenuItem = $ModelResult<$Schema, "CmsMenuItem">;
export type DonationFund = $ModelResult<$Schema, "DonationFund">;
export type PavilionReservableItem = $ModelResult<$Schema, "PavilionReservableItem">;
export type PavilionReservableItemPrice = $ModelResult<$Schema, "PavilionReservableItemPrice">;
export type PavilionReservationRequest = $ModelResult<$Schema, "PavilionReservationRequest">;
export type PavilionReservationSlot = $ModelResult<$Schema, "PavilionReservationSlot">;
export type PavilionReservationService = $ModelResult<$Schema, "PavilionReservationService">;
export type LegacyMysqlSyncRun = $ModelResult<$Schema, "LegacyMysqlSyncRun">;
export type StaffMember = $ModelResult<$Schema, "StaffMember">;
export type AuthContext = $TypeDefResult<$Schema, "AuthContext">;
export const AppRole = $schema.enums.AppRole.values;
export type AppRole = (typeof AppRole)[keyof typeof AppRole];
export const ThemePreference = $schema.enums.ThemePreference.values;
export type ThemePreference = (typeof ThemePreference)[keyof typeof ThemePreference];
export const SailingAffiliation = $schema.enums.SailingAffiliation.values;
export type SailingAffiliation = (typeof SailingAffiliation)[keyof typeof SailingAffiliation];
export const MitDataWarehousePersonType = $schema.enums.MitDataWarehousePersonType.values;
export type MitDataWarehousePersonType = (typeof MitDataWarehousePersonType)[keyof typeof MitDataWarehousePersonType];
export const EventSailingCardRequirement = $schema.enums.EventSailingCardRequirement.values;
export type EventSailingCardRequirement = (typeof EventSailingCardRequirement)[keyof typeof EventSailingCardRequirement];
export const LegalAgreementAcceptanceSource = $schema.enums.LegalAgreementAcceptanceSource.values;
export type LegalAgreementAcceptanceSource = (typeof LegalAgreementAcceptanceSource)[keyof typeof LegalAgreementAcceptanceSource];
export const SailingCardRequestStatus = $schema.enums.SailingCardRequestStatus.values;
export type SailingCardRequestStatus = (typeof SailingCardRequestStatus)[keyof typeof SailingCardRequestStatus];
export const SailingCardType = $schema.enums.SailingCardType.values;
export type SailingCardType = (typeof SailingCardType)[keyof typeof SailingCardType];
export const UserAuditAction = $schema.enums.UserAuditAction.values;
export type UserAuditAction = (typeof UserAuditAction)[keyof typeof UserAuditAction];
export const NewsletterListDefaultSubscription = $schema.enums.NewsletterListDefaultSubscription.values;
export type NewsletterListDefaultSubscription = (typeof NewsletterListDefaultSubscription)[keyof typeof NewsletterListDefaultSubscription];
export const NewsletterListVisibility = $schema.enums.NewsletterListVisibility.values;
export type NewsletterListVisibility = (typeof NewsletterListVisibility)[keyof typeof NewsletterListVisibility];
export const NewsletterSubscriberSuppressionReason = $schema.enums.NewsletterSubscriberSuppressionReason.values;
export type NewsletterSubscriberSuppressionReason = (typeof NewsletterSubscriberSuppressionReason)[keyof typeof NewsletterSubscriberSuppressionReason];
export const NewsletterSubscriptionStatus = $schema.enums.NewsletterSubscriptionStatus.values;
export type NewsletterSubscriptionStatus = (typeof NewsletterSubscriptionStatus)[keyof typeof NewsletterSubscriptionStatus];
export const NewsletterBroadcastStatus = $schema.enums.NewsletterBroadcastStatus.values;
export type NewsletterBroadcastStatus = (typeof NewsletterBroadcastStatus)[keyof typeof NewsletterBroadcastStatus];
export const NewsletterDeliveryStatus = $schema.enums.NewsletterDeliveryStatus.values;
export type NewsletterDeliveryStatus = (typeof NewsletterDeliveryStatus)[keyof typeof NewsletterDeliveryStatus];
export const NewsletterEventType = $schema.enums.NewsletterEventType.values;
export type NewsletterEventType = (typeof NewsletterEventType)[keyof typeof NewsletterEventType];
export const EventDetailPageKind = $schema.enums.EventDetailPageKind.values;
export type EventDetailPageKind = (typeof EventDetailPageKind)[keyof typeof EventDetailPageKind];
export const EventRegistrationMode = $schema.enums.EventRegistrationMode.values;
export type EventRegistrationMode = (typeof EventRegistrationMode)[keyof typeof EventRegistrationMode];
export const EventAddressPreset = $schema.enums.EventAddressPreset.values;
export type EventAddressPreset = (typeof EventAddressPreset)[keyof typeof EventAddressPreset];
export const EventRegistrationStatus = $schema.enums.EventRegistrationStatus.values;
export type EventRegistrationStatus = (typeof EventRegistrationStatus)[keyof typeof EventRegistrationStatus];
export const EventAnswerType = $schema.enums.EventAnswerType.values;
export type EventAnswerType = (typeof EventAnswerType)[keyof typeof EventAnswerType];
export const PaymentStatus = $schema.enums.PaymentStatus.values;
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
export const PaymentPurpose = $schema.enums.PaymentPurpose.values;
export type PaymentPurpose = (typeof PaymentPurpose)[keyof typeof PaymentPurpose];
export const PaymentSource = $schema.enums.PaymentSource.values;
export type PaymentSource = (typeof PaymentSource)[keyof typeof PaymentSource];
export const EventPaymentNotificationKind = $schema.enums.EventPaymentNotificationKind.values;
export type EventPaymentNotificationKind = (typeof EventPaymentNotificationKind)[keyof typeof EventPaymentNotificationKind];
export const SailingRatingRuleType = $schema.enums.SailingRatingRuleType.values;
export type SailingRatingRuleType = (typeof SailingRatingRuleType)[keyof typeof SailingRatingRuleType];
export const CmsMediaStatus = $schema.enums.CmsMediaStatus.values;
export type CmsMediaStatus = (typeof CmsMediaStatus)[keyof typeof CmsMediaStatus];
export const CmsMediaKind = $schema.enums.CmsMediaKind.values;
export type CmsMediaKind = (typeof CmsMediaKind)[keyof typeof CmsMediaKind];
export const CmsMediaStorageProvider = $schema.enums.CmsMediaStorageProvider.values;
export type CmsMediaStorageProvider = (typeof CmsMediaStorageProvider)[keyof typeof CmsMediaStorageProvider];
export const CmsBlockKind = $schema.enums.CmsBlockKind.values;
export type CmsBlockKind = (typeof CmsBlockKind)[keyof typeof CmsBlockKind];
export const CmsMenuLocation = $schema.enums.CmsMenuLocation.values;
export type CmsMenuLocation = (typeof CmsMenuLocation)[keyof typeof CmsMenuLocation];
export const PavilionReservationPersona = $schema.enums.PavilionReservationPersona.values;
export type PavilionReservationPersona = (typeof PavilionReservationPersona)[keyof typeof PavilionReservationPersona];
export const PavilionReservationStatus = $schema.enums.PavilionReservationStatus.values;
export type PavilionReservationStatus = (typeof PavilionReservationStatus)[keyof typeof PavilionReservationStatus];
export const PavilionReservationPaymentStatus = $schema.enums.PavilionReservationPaymentStatus.values;
export type PavilionReservationPaymentStatus = (typeof PavilionReservationPaymentStatus)[keyof typeof PavilionReservationPaymentStatus];
export const PavilionReservableItemKind = $schema.enums.PavilionReservableItemKind.values;
export type PavilionReservableItemKind = (typeof PavilionReservableItemKind)[keyof typeof PavilionReservableItemKind];
export const PavilionPricingType = $schema.enums.PavilionPricingType.values;
export type PavilionPricingType = (typeof PavilionPricingType)[keyof typeof PavilionPricingType];
export const LegacyMysqlSyncStatus = $schema.enums.LegacyMysqlSyncStatus.values;
export type LegacyMysqlSyncStatus = (typeof LegacyMysqlSyncStatus)[keyof typeof LegacyMysqlSyncStatus];
