server {
  listen 8080;
  server_name _;

  location = /cms-media/healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 204;
  }

  location /cms-media/ {
    alias /var/lib/mitsailing/cms-media/ready/;
    try_files $uri =404;

    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Content-Security-Policy "default-src 'none'; img-src 'self'; media-src 'self'; style-src 'none'; script-src 'none'; sandbox";
    add_header X-Content-Type-Options nosniff;
  }
}
