name: Checkly

on: [deployment_status]

env:
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
  CHECKLY_REPO_URL: https://github.com/mitsailing/mitsailing
  CHECKLY_TEST_ENVIRONMENT: production
  ENVIRONMENT_URL: https://mitsailing.com

jobs:
  test-e2e:
    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Only run after a successful production deployment.
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'production'

    name: Test E2E on Checkly
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
        with:
          ref: '${{ github.event.deployment_status.deployment.ref }}'
          fetch-depth: 0

      - name: Set Checkly git metadata
        run: |
          echo "CHECKLY_REPO_BRANCH=${{ github.event.deployment_status.deployment.ref }}" >> "$GITHUB_ENV"
          echo "CHECKLY_REPO_SHA=${{ github.event.deployment_status.deployment.sha }}" >> "$GITHUB_ENV"

      - name: Set up Node.js environment
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run checks # run the checks passing in the ENVIRONMENT_URL and recording a test session.
        id: run-checks
        run: npx dotenv -c production -- npx checkly test --reporter=github --record

      - name: Create summary # export the markdown report to the job summary.
        id: create-summary
        run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY

      - name: Deploy checks # if the test run was successful and we are on production, deploy the checks
        id: deploy-checks
        if: steps.run-checks.outcome == 'success'
        run: npx dotenv -c production -- npx checkly deploy --force
